test:
  saas:
    host: 39.107.43.201
    user: root
    password: dJ_xw2ve_Dc9_1OiY3
    port: 9919
    db: sandbox_saas

  steamrunner:
    host: 39.107.43.201
    user: root
    password: dJ_xw2ve_Dc9_1OiY3
    port: 9919
    db: sandbox_saas_steamrunner

  pay:
    host: 47.94.212.153
    user: root
    password: dJ_xw2ve_Dc9_1OiY3
    port: 9919
    db: ifc_eridanus

  redis:
    host: 39.107.43.201
    password: j_dR29nz1Z
    port: 9917
    db: 15

qa:
  saas:
    host: 47.95.198.135
    user: sandbox
    password: TxHT29VMfn4ZJ6VU!
    port: 3306
    db: sandbox_saas

  steamrunner:
    host: 47.95.198.135
    user: sandbox
    password: TxHT29VMfn4ZJ6VU!
    port: 3306
    db: sandbox_saas_steamrunner

  pay:
    host: 47.94.212.153
    user: root
    password: dJ_xw2ve_Dc9_1OiY3
    port: 9919
    db: ifc_eridanus
    decode_responses: True

  redis:
    host: db-qa.cloudloan.com
    password: /;p09ol.,kjM
    port: 6379
    db: 15
    decode_responses: True