# -*- coding: UTF-8 -*-
"""
@auth:buxiangjie
@date:2021-03-22 11:26:00
@describe: entity
"""
from enum import Enum


class EntityInfo(Enum):
	jfx_credit = {
		"cityGrading": 2,
		"companyScale": 1,
		"enterpriseCertificateType": 1,
		"clinicOriginalLevel": 3,
		"monthPatients": 50,
		"clinicTradingLevel": 4,
		"permitRegistrationNumber": "000000000000000000",
		"isHighRiskArea": 0,
		"establishYears": 1,
		"jfxHistoryCreditAmount": 150000.0,
		"registerDetailAddress": "详细地址",
		"businessLicenseValidDate": "2020-01-01-2021-01-01",
		"clinicHistoryCreditAmount": 288888.0,
		"jfxHistoryOrderNum": 5,
		"purchaseTimesInRecentYears": 1,
		"isFieldTrip": 1,
		"cooperationalYears": 2,
		"supplierUnifiedSocialCreditCode": "12839914915",
		"isAddressConsistent": 1,
		"clinicTotalLoanCount": 10,
		"registerAddressProvince": "110000",
		"clinicHistorySupplierNum": 12,
		"sourceUserProductType": 1,
		"registerAddressCity": "110100",
		"clinicOverdueTimesMoreThan5": 0,
		"supplierName": "经销商",
		"brandName": "品牌名称",
		"otherInspectionEquipment": "高端设备",
		"decorateGrade": 1,
		"annualPlantingNumber": 130,
		"purchaseAmountInRecentYears": 1,
		"inspectionEquipment": "4",
		"clinicFirstLoanDate": "2021-01-02",
		"clinicalMedicalResources": 1,
		"clinicCurrentOverdueDays": 20,
		"chairNumber": 10,
		"registerAddressBorough": "110105",
		"clinicTotalLoanAmount": 1111.12,
		"supplierOriginalLevel": 6,
		"supplierTradingLevel": 5,
		"enterpriseCertificateNum": "6323272466301355006",
		"hospitalCategory": 1
	}
	jfx_project = {
		"supplierLegalPersonPhone": "15533330202",
		"clinicOriginalLevel": 1,
		"monthPatients": 50,
		"supplierLegalPersonIdcard": "372301199509074811",
		"clinicTradingLevel": 2,
		"permitRegistrationNumber": "000000000000000000",
		"loanUsageInfo": {
			"totalAmount": 200000.0,
			"allProductNumber": 2,
			"date": "2019-01-01",
			"saleProductDetailList": [{
				"unitPriceAmount": 100000.0,
				"productName": "产品名称123",
				"singleProductNumber": 5
			}, {
				"unitPriceAmount": 200000.0,
				"productName": "产品名称456",
				"singleProductNumber": 3
			}]
		},
		"supplierAccessWay": 1,
		"supplierLegalPersonName": "经销商法人",
		"doctorNumber": 3,
		"downPayment": 5555.55,
		"supplierUnifiedSocialCreditCode": "485919032",
		"supplierLowestDepositPayment": 11111.0,
		"supplierName": "经销商名称",
		"supplierDepositLowestRate": 1.11,
		"supplierEstablishYears": 1,
		"supplierProprietorRealCityLevel": 1,
		"consumeAmount": 3333.33,
		"supplierProprietorRealCity": "110000",
		"annualPlantingNumber": 130,
		"inspectionEquipment": "1,2,4",
		"supplierCompanyBadAccountRate": 3.33,
		"chairNumber": 10,
		"supplierOriginalLevel": 0,
		"supplierTradingLevel": 0
	}
	jk_ckshd_credit = {
		"cityGrading": 1,
		"unifiedSocialCreditCode": "178199873022801",
		"proprietorIsDoctor": 1,
		"accessWay": 1,
		"permitRegistrationNumber": "84819923",
		"isThreeCertificatesInOne": "Y",
		"clinicMaxOverdueDays": 1,
		"clinicTotalOverdueTimes": 1,
		"isFieldTrip": "Y",
		"clinicHistoryOverdueDays": 1,
		"isAddressConsistent": "Y",
		"legalPersonPhoneRealName": "Y",
		"registerAddressCity": "110100",
		"clinicOverdueTimesMoreThan5": 1,
		"brandName": "品牌名称",
		"isChangeForLegalPerson": 1,
		"authorisedRepresentative": 1,
		"contactName": "联系人",
		"proprietorRealPhone": "12345678900",
		"chainInstitutionNumber": 2,
		"locationGrade": 1,
		"isSamePersonForProprietorAndLegal": "Y",
		"proprietorRealIdCardNo": "372301199509074811",
		"registeredAssets": 100.05,
		"oldLegalPersonName": "原法人",
		"floorSpace": 21.55,
		"hospitalCategory": 1,
		"clinicName": "诊所名称",
		"clinicCurrentOverdueAmount": 100.55,
		"proprietorRealName": "实际经营者",
		"isSamePersonForLegalAndContact": "Y",
		"establishYears": 3,
		"contactIdCardNo": "372301199509074811",
		"staffOnActiveDutyNum": 1,
		"clinicCurrentOverdueCount": 1,
		"registerDetailAddress": "北京市海淀区xxx街道xxx小区xxx号楼xxx层xxx室",
		"businessLicenseValidDate": "2029-12-10-9999-09-09",
		"clinicTotalSettleCount": 1,
		"clinicFirstLoanTime": "2021-02-24 00:00:00",
		"clinicTotalLoanCount": 1,
		"registerAddressProvince": "110100",
		"legalPersonIsDoctor": 1,
		"operateSiteOwnership": 1,
		"proprietorIsPhoneRealName": "Y",
		"supplierName": "供应商1,供应商2",
		"havePromotionActivity": 1,
		"isRequiredApplyLicense": "Y",
		"decorateGrade": 1,
		"clinicInLoanAmount": 100.55,
		"isSamePersonForProprietorContact": "Y",
		"clinicCurrentOverdueDays": 1,
		"registerAddressBorough": "110105",
		"clinicTotalLoanAmount": 100.55,
		"contactPhone": "12345678900"
	}
	jk_ckshd_project = {
		"supplierName": "供应商名称",
		"consigneeName": "收货人",
		"supplierUnifiedSocialCreditCode": "1823994",
		"consigneePhone": "13800138003",
		"merchantDiscountRate": 0.12,
		"productInfoList": [{
			"productName": "产品名称",
			"brandName": "品牌名称",
			"productModel": "产品型号",
			"productQuantity": 10,
			"productUnitPrice": 100
		}]
	}
	jk_cwshd_credit = {
		"cityGrading": 1,
		"proprietorIsDoctor": 1,
		"monthPatients": 1,
		"accessWay": 1,
		"permitRegistrationNumber": "192030304",
		"corpType": 1,
		"proprietorRealName": "实际经营者",
		"isThreeCertificatesInOne": "Y",
		"establishYears": 3,
		"staffOnActiveDutyNum": 1,
		"registerDetailAddress": "北京市海淀区xxx街道xxx小区xxx号楼xxx层xxx室",
		"businessLicenseValidDate": "9999-09-09",
		"doctorNumber": 3,
		"supplierUnifiedSocialCreditCode": "32849935",
		"isAddressConsistent": "Y",
		"legalPersonPhoneRealName": "Y",
		"registerAddressProvince": "110100",
		"legalPersonIsDoctor": 1,
		"registerAddressCity": "110100",
		"proprietorIsPhoneRealName": "Y",
		"shareholderIsDoctor": 1,
		"supplierName": "供应商",
		"brandName": "品牌名称",
		"isChangeForLegalPerson": 1,
		"decorateGrade": 1,
		"proprietorRealPhone": "15533330101",
		"locationGrade": 1,
		"chainInstitutionNumber": 2,
		"isSamePersonForProprietorAndLegal": "Y",
		"proprietorRealIdCardNo": "372301199509074811",
		"registeredAssets": 111.11,
		"manageTime": 5,
		"registerAddressBorough": "110500",
		"hasCertificateNumberOfPeople": 5,
		"floorSpace": 21.11,
		"oldLegalPersonName": "原法人姓名",
		"consultationRoomNumber": 7,
		"hospitalCategory": 1,
		"monitorDevice": "ct"
	}
	jk_cwshd_project = {
		"cityGrading": 1,
		"proprietorIsDoctor": 1,
		"monthPatients": 1,
		"accessWay": 2,
		"permitRegistrationNumber": "5849134",
		"proprietorRealName": "实际经营者",
		"deliveryAddressBorough": "110500",
		"isThreeCertificatesInOne": "Y",
		"establishYears": 3,
		"merchantDiscountRate": 0.120005,
		"registerDetailAddress": "北京市海淀区xxx街道xxx小区xxx号楼xxx层xxx室",
		"consigneeName": "收货联系人",
		"businessLicenseValidDate": "2029-12-10-9999-09-09",
		"doctorNumber": 1,
		"supplierUnifiedSocialCreditCode": "9499123004",
		"consigneePhone": "13800138003",
		"isAddressConsistent": "Y",
		"legalPersonPhoneRealName": "Y",
		"registerAddressProvince": "110100",
		"legalPersonIsDoctor": 1,
		"registerAddressCity": "110100",
		"proprietorIsPhoneRealName": "Y",
		"shareholderIsDoctor": 1,
		"supplierName": "XXX",
		"deliveryAddressProvince": "110100",
		"brandName": "品牌名称",
		"deliveryDetailAddress": "北京市海淀区xxx街道xxx小区xxx号楼xxx层xxx室",
		"isChangeForLegalPerson": 1,
		"decorateGrade": 1,
		"productInfoList": [{
			"productName": "产品名称",
			"brandName": "品牌名称",
			"productQuantity": 10,
			"productUnitPrice": 100.55
		}],
		"proprietorRealPhone": "12345678900",
		"locationGrade": 1,
		"isSamePersonForProprietorAndLegal": "Y",
		"proprietorRealIdCardNo": "123456789000000000",
		"registeredAssets": 100.05,
		"manageTime": 5,
		"registerAddressBorough": "110500",
		"hasCertificateNumberOfPeople": 1,
		"deliveryAddressCity": "110100",
		"floorSpace": 21.55,
		"oldLegalPersonName": "原法人",
		"consultationRoomNumber": 1,
		"hospitalCategory": 1,
		"monitorDevice": "宠物医院设备"
	}
	wxjk_project = {
		"livePhone": "1012345678",
		"faceRecognition": "Y",
		"currentCity": "110000",
		"cardValidDate": "2019-12-10-9999-09-09"
	}